### PR TITLE
Remove download changes

### LINKED ISSUE #78: Fix test WC_Tests_Product_CSV_Importer::test_import()
This test is failing with the following error message:

```
5) WC_Tests_Product_CSV_Importer::test_import
Failed asserting that 6 matches expected 7.

wp-content/plugins/woocommerce/tests/unit-tests/importer/product.php:96
```

### PR DESCRIPTION
**Pull request by rodrigoprimo**
Early in the development of this plugin, we decided to store download limit and download expiry per file instead of per product as WC core does. This is a nice change to have but probably something to do first in WC core to make sure the plugin is fully compatible with it. So this commit removes all the changes that were required to implement download limit and download expiry per file and adds two new fields to wp_wc_products to store this information per product.

There is some ongoing discussion in #89 about what would be the best approach. If we should remove the download limit and download expiry per file functionally or if we should keep it and fixes the remaining issues. I decided to check how complex it was to remove it and I'm creating this PR to show the necessary changes and to contribute to the conversation. We need to make a decision before merging or closing this PR.

To test this PR it is necessary to recreate the plugin tables using `wp wc-product-tables recreate-tables`.

Fixes #78, #80

cc @kloon  @claudiosanches

### CODE REVIEW

File: includes/class-wc-product-tables-install.php [hunk 1]
```diff
@@ -49,6 +49,8 @@ public static function activate() {
 			  `type` varchar(100) NULL default 'simple',
 			  `virtual` tinyint(1) NULL default 0,
 			  `downloadable` tinyint(1) NULL default 0,
+			  `download_limit` int(11) default NULL,
```
Comment (claudiosanches) [inline includes/class-wc-product-tables-install.php]: This is exactly what I'm afraid to do, moving to this table, because once here, will be very hard to move this data again for a third time.

Comment (rodrigoprimo) [reply includes/class-wc-product-tables-install.php]: I agree that moving this data is not trivial but I really don't think we should change to download limit and download expiry in this plugin before we make this change in core. This is just my personal opinion.

Comment (claudiosanches) [reply includes/class-wc-product-tables-install.php]: But this is exactly the reason why we started doing it, to not have it in this table and to avoid the trouble of moving this data twice.

**Comment by rodrigoprimo** [comment]
I spoke with @claudiosanches and we decided to keep download limit and download expiry as a post meta. This information is not used often so it is unlikely to impact performance. Once WC core changes to use download limit and download expiry per file we can revisit this idea in this plugin.
